services:
  scraper:
    build:
      context: ../services/scraper
    volumes:
      - ../data:/data

  pdf_processor:
    build:
      context: ../services/pdf_processor
    volumes:
      - ../data:/data
    depends_on:
      - scraper
